# Data processing for Cereals
# Setup
## Library import
We import all the required Python libraries

In [65]:
import numpy as np
import pandas as pd
import geopandas as gpd

## Read data
**Comunidades autonomas**

In [66]:
comunidades = gpd.read_file(f'../../datasets/processed/comunidades.geojson')
comunidades.sort_values(['CO_CCAA'], inplace = True)
comunidades

,CO_CCAA,DS_CCAA,geometry
0,1,Andalucía,"MULTIPOLYGON (((-3.03243 35.94046, -3.03242 35..."
8,10,Extremadura,"POLYGON ((-6.36166 38.04027, -6.36172 38.04058..."
9,11,Galicia,"MULTIPOLYGON (((-8.88814 41.97151, -8.88848 41..."
10,12,Comunidad de Madrid,"MULTIPOLYGON (((-3.67839 40.13910, -3.67872 40..."
11,13,Región de Murcia,"MULTIPOLYGON (((-0.70831 37.61951, -0.70828 37..."
12,14,Comunidad Foral de Navarra,"MULTIPOLYGON (((-1.14471 42.43736, -1.14484 42..."
13,15,Pais Vasco,"MULTIPOLYGON (((-2.49429 42.59738, -2.49407 42..."
14,16,La Rioja,"POLYGON ((-2.05267 41.95100, -2.05340 41.95142..."
15,17,Comunidad Valenciana,"MULTIPOLYGON (((-0.76151 37.84860, -0.76136 37..."
1,2,Aragón,"POLYGON ((-0.61193 40.12283, -0.61455 40.11969..."
2,3,Principado de Asturias,"MULTIPOLYGON (((-6.36457 43.05207, -6.36450 43..."
3,4,Islas Baleares,"MULTIPOLYGON (((1.42260 38.66365, 1.42256 38.6..."
4,6,Cantabria,"MULTIPOLYGON (((-3.89105 43.04166, -3.89264 43..."
5,7,Castilla La Mancha,"MULTIPOLYGON (((-2.76292 38.53218, -2.76361 38..."
6,8,Castilla y León,"MULTIPOLYGON (((-5.34895 40.26520, -5.35057 40..."
7,9,Cataluña,"MULTIPOLYGON (((0.70227 40.63800, 0.70225 40.6..."

**Rendimiento cereales**

In [67]:
df = pd.read_excel('../../datasets/raw/crops/cereales/CEREALES _clean.xlsx')
df = pd.merge(comunidades[['CO_CCAA', 'DS_CCAA']], df, how='left', left_on='DS_CCAA', right_on='Comunidad autonoma')
df.drop(columns=['Comunidad autonoma', 'Codigo'], inplace=True)
df

,CO_CCAA,DS_CCAA,Trigo 45,Girasol 45,Cebada 45,Maiz 45,Trigo 85,Girasol 85,Cebada 85,Maiz 85
0,1,Andalucía,-0.165048,-0.192895,0.006925,-0.172530,-0.157145,-0.193500,-0.008091,-0.176795
1,10,Extremadura,-0.058572,NaN,-0.015351,NaN,-0.148604,NaN,-0.097235,NaN
2,11,Galicia,0.098262,-0.149709,0.097255,0.034379,-0.033942,-0.244170,0.099842,0.034380
3,12,Comunidad de Madrid,-0.147850,NaN,0.058388,NaN,-0.157837,NaN,0.020724,NaN
4,13,Región de Murcia,-0.144359,NaN,-0.009289,NaN,-0.124758,NaN,-0.032264,NaN
5,14,Comunidad Foral de Navarra,-0.061915,-0.134478,0.050899,-0.042062,-0.051769,-0.183847,0.067655,-0.044001
6,15,Pais Vasco,0.020524,-0.191743,0.079689,-0.004093,0.007711,-0.223985,0.110507,0.006517
7,16,La Rioja,-0.037724,-0.145564,0.059753,-0.019447,-0.054183,-0.150960,0.071689,-0.019395
8,17,Comunidad Valenciana,-0.163181,-0.136290,0.011242,-0.053320,-0.158251,-0.231250,-0.019372,-0.041080
9,2,Aragón,-0.099414,-0.161043,0.046745,-0.060264,-0.099022,-0.196272,0.041403,-0.059152
10,3,Principado de Asturias,0.021996,-0.145620,0.096395,0.019718,0.042341,-0.149107,0.116277,0.008543
11,4,Islas Baleares,NaN,NaN,-0.012410,-0.153470,NaN,NaN,-0.007063,-0.124040
12,6,Cantabria,0.067871,-0.069540,0.083500,-0.019765,0.047377,-0.114688,0.096325,-0.037667
13,7,Castilla La Mancha,-0.096164,NaN,0.022800,-0.042580,-0.146954,NaN,-0.012362,-0.035580
14,8,Castilla y León,-0.039520,-0.218446,0.077640,0.030311,-0.096913,-0.234772,0.065682,0.016605
15,9,Cataluña,-0.093082,-0.021136,0.047130,-0.088832,-0.085564,-0.063903,0.052096,-0.096608

In [71]:
columns = list(df.columns)
df_new = pd.DataFrame(columns=['CO_CCAA', 'DS_CCAA', 'dataset', 'indicator', 'scenario', 'value', 'cereal', 'unit'])
for i in np.arange(4)+2:
    df_tmp = pd.concat([df[['CO_CCAA', 'DS_CCAA']], df[['CO_CCAA', 'DS_CCAA']]])
    df_tmp['scenario'] = len(df) * ['rcp45'] + len(df) * ['rcp85']
    df_tmp['value'] = list(df[columns[i]]*100) + list(df[columns[i+4]]*100)
    df_tmp['cereal'] = columns[i].split(' ')[0]
    df_tmp['unit'] = '%'
    df_tmp['dataset'] = 'PESETA'
    df_tmp['indicator'] = 'Rendimiento'

    df_new = pd.concat([df_new, df_tmp])
df_new.reset_index(drop=True, inplace=True)

In [72]:
df_new

,CO_CCAA,DS_CCAA,dataset,indicator,scenario,value,cereal,unit
0,1,Andalucía,PESETA,Rendimiento,rcp45,-16.504750,Trigo,%
1,10,Extremadura,PESETA,Rendimiento,rcp45,-5.857250,Trigo,%
2,11,Galicia,PESETA,Rendimiento,rcp45,9.826222,Trigo,%
3,12,Comunidad de Madrid,PESETA,Rendimiento,rcp45,-14.785000,Trigo,%
4,13,Región de Murcia,PESETA,Rendimiento,rcp45,-14.435875,Trigo,%
...,...,...,...,...,...,...,...,...
123,4,Islas Baleares,PESETA,Rendimiento,rcp85,-12.404000,Maiz,%
124,6,Cantabria,PESETA,Rendimiento,rcp85,-3.766700,Maiz,%
125,7,Castilla La Mancha,PESETA,Rendimiento,rcp85,-3.558000,Maiz,%
126,8,Castilla y León,PESETA,Rendimiento,rcp85,1.660500,Maiz,%
127,9,Cataluña,PESETA,Rendimiento,rcp85,-9.660800,Maiz,%

**Save table**

In [75]:
df_new.to_csv(f'../../datasets/processed/cereal_indicators/cereal_indicators_comunidades_autonomas.csv', index=False)